name: rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        activerecord:
          - '4.1'
          - '5.0'
          - '6.0'
          - '6.1'
          - '7.0'
          - '8.0'
        exclude:
        # active record 4.1 is not compatible with ruby 2.7 due to BigDecimal changes
        - ruby: '2.7'
          activerecord: '4.1' 
        # ActiveRecord 5.x doesn't work on Ruby 3.0+
        - ruby: '3.0'
          activerecord: '4.1'
        - ruby: '3.0'
          activerecord: '5.0'
        - ruby: '3.1'
          activerecord: '4.1'
        - ruby: '3.1'
          activerecord: '5.0'
        - ruby: '3.2'
          activerecord: '4.1'
        - ruby: '3.2'
          activerecord: '5.0'
        - ruby: '3.3'
          activerecord: '4.1'
        - ruby: '3.3'
          activerecord: '5.0'
        # ActiveRecord 7.x doesn't work on Ruby 2.6 and below
        - ruby: '2.6'
          activerecord: '7.0'
        # Ruby 3.1 has problem with Rails 7 currently (https://gist.github.com/yahonda/2776d8d7b6ea7045359f38c10449937b#add-classdescendants)
        - ruby: '3.1'
          activerecord: '7.0'
        # Activerecord 8.x doesn't work on Ruby 3.1 and below
        - ruby: '2.6'
          activerecord: '8.0'
        - ruby: '2.7'
          activerecord: '8.0'
        - ruby: '3.0'
          activerecord: '8.0'
        - ruby: '3.1'
          activerecord: '8.0'


    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Install sqlite3 on system
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.4.22'
    
    - name : Install dependency
      run: |
        bundle _2.4.22_ install
        
    - name: Run appraisal to install different active records version
      run: |
        bundle _2.4.22_ exec appraisal install
        
    - name: Run rspec test across active record
      run: |
        bundle _2.4.22_ exec appraisal activerecord-${{ matrix.activerecord }} rspec

    